### ISSUE TITLE
PDTree: OrderBy

### ISSUE THREAD

**Issue by davidnmbond** [panoramicdata/PanoramicData.Blazor#9]
It should be possible to order nodes at any given level in PDTree using a lambda.  This would facilitate renaming a node and having it automatically re-order.

Not specifying this should leave the existing order.

**Comment by elylv** [comment]
Would be great if we were able to two-way bind to the display order, also, so that if we drag/drop a node, its display order within the tree is updated.  I guess this would lead to the possibility that some or all of the nodes' display order would also be updated to accommodate the new display order of the dragged node.

**Comment by davidnmbond** [comment]
@elylv, that would not be possible if a lambda is used.

However, I agree that optionally, INSTEAD it should be possible to drag-and-drop nodes to nodes (to move a node to a child node of another node) OR the gaps between nodes and that this should trigger an event.  I will raise another issue for that.

**Comment by MarkGoldring** [comment]
Have added PDTree.Sort parameter that accepts a sort function (or lambda) to build 1.0.69.
